### ISSUE TITLE
address pytest warnings

### ISSUE THREAD

**Issue by peisenha** [OpenSourceEconomics/norpy#18]
/home/peisenha/external_storage/ownCloud/office/workspace/OpenSourceEconomics/norpy/norpy/tests/test_property.py:157: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
    assert input_output_size[0][input_output_size[1]] != np.array(

-- Docs: https://docs.pytest.org/en/latest/warnings.html

**Comment by mo2561057** [comment]
done
