### ISSUE TITLE
please add yaml package to environment files

### ISSUE THREAD

**Issue by peisenha** [OpenSourceEconomics/norpy#19]
__________________________ ERROR collecting norpy/tests/test_property_2.py ___________________________
ImportError while importing test module '/home/peisenha/external_storage/ownCloud/office/workspace/OpenSourceEconomics/norpy/norpy/tests/test_property_2.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
norpy/tests/test_property_2.py:23: in <module>
    from norpy.model_spec import get_random_model_specification, get_model_obj
/home/peisenha/OpenSourceEconomics/norpy/norpy/model_spec.py:9: in <module>
    import yaml
E   ModuleNotFoundError: No module named 'yaml'
__________________________ ERROR collecting norpy/tests/test_regression.py ___________________________
ImportError while importing test module '/home/peisenha/external_storage/ownCloud/office/workspace/OpenSourceEconomics/norpy/norpy/tests/test_regression.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
norpy/tests/test_regression.py:12: in <module>
    from norpy.model_spec import get_model_obj, get_random_model_specification
/home/peisenha/OpenSourceEconomics/norpy/norpy/model_spec.py:9: in <module>
    import yaml
E   ModuleNotFoundError: No module named 'yaml'

**Comment by mo2561057** [comment]
I added pyyaml to environment.yaml. I think this can be closed !
