### ISSUE TITLE
access to simulate function

### ISSUE THREAD

**Issue by peisenha** [OpenSourceEconomics/norpy#23]
Please modify the main `__init__` so that we can do the following directly:

```
import norpy
model_obj = norpy.get_model_obj()

norpy.simulate(model_obj)
```
See here for an example https://github.com/OpenSourceEconomics/soepy/blob/master/soepy/__init__.py

and reach out to @boryana-ilieva  if needed.

**Comment by mo2561057** [comment]
Done
