### ISSUE TITLE
potentially flawed index

### ISSUE THREAD

**Issue by peisenha** [OpenSourceEconomics/norpy#28]
https://github.com/OpenSourceEconomics/norpy/blob/693d7b7df23367c8b44e207bb4607d50d90550c3/norpy/solve/norpy_hatchery.f90#L258

Please comment on why it is `i - 1`and not just `i`.

**Comment by mo2561057** [comment]
OK I think this is just wrong! I might have confused fortran with python indexing ! It probably didnt make a difference since I just set these to zero in the tests

**Comment by peisenha** [comment]
but in the random initialization files they are varying freely, right? Please set up and test and quick PR that fixes this and then I will merge it back into this branch and let me know if it breaks the regression tests.

**Comment by mo2561057** [comment]
Will do

**Comment by peisenha** [comment]
Solved
