### ISSUE TITLE
move specification into initialization file

### ISSUE THREAD

**Issue by peisenha** [OpenSourceEconomics/norpy#31]
https://github.com/OpenSourceEconomics/norpy/blob/693d7b7df23367c8b44e207bb4607d50d90550c3/norpy/simulate/simulate.py#L152

**Comment by mo2561057** [comment]
So there should be a second object that specifies simulation parameters ?

**Comment by peisenha** [comment]
Please consult https://respy.readthedocs.io/en/latest/software/model-specification.html some inspiration.
