### ISSUE TITLE
performand compilation of f2py code

### ISSUE THREAD

**Issue by peisenha** [OpenSourceEconomics/norpy#53]
https://github.com/OpenSourceEconomics/norpy/blob/c202b9bf010ad2f3ea0809c1b450e2cfd09c0f3b/norpy/solve/wscript#L14

We need to make `-fcheck=all -fbacktrace` optional as it slows the code down.

**Comment by mo2561057** [comment]
We already have a debug flag for waf that included fcheck= all and -backtrace. I delted both out of the extra args. Whenever we need these we can compile waf with a debug flag.
